//
//  VideoFeedPresenter.swift
//  SSPrototype
//
//  Created by Narong Kanthanu on 22/10/2561 BE.
//  Copyright (c) 2561 Narong Kanthanu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VideoFeedPresentationLogic {
    func presentVideoFeed(response: VideoFeed.VideoFeed.Response)
    func presentVideoFeedIsEmpty()
}

class VideoFeedPresenter: VideoFeedPresentationLogic {
    weak var viewController: VideoFeedDisplayLogic?
    
    func presentVideoFeed(response: VideoFeed.VideoFeed.Response) {
        let viewModel = VideoFeed.VideoFeed.ViewModel(videoFeedList: response.videoFeedList)
        viewController?.displayVideoFeed(viewModel: viewModel)
    }
    
    func presentVideoFeedIsEmpty() {
        viewController?.displayVideoFeedIsEmpty()
    }
    
}
