//
//  VideoFeedWorker.swift
//  SSPrototype
//
//  Created by Narong Kanthanu on 22/10/2561 BE.
//  Copyright (c) 2561 Narong Kanthanu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class VideoFeedWorker
{
  func doSomeWork()
  {
  }
}
