//
//  VideoFeedRouter.swift
//  SSPrototype
//
//  Created by Narong Kanthanu on 22/10/2561 BE.
//  Copyright (c) 2561 Narong Kanthanu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VideoFeedRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol VideoFeedDataPassing
{
  var dataStore: VideoFeedDataStore? { get }
}

class VideoFeedRouter: NSObject, VideoFeedRoutingLogic, VideoFeedDataPassing
{
  weak var viewController: VideoFeedViewController?
  var dataStore: VideoFeedDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: VideoFeedViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: VideoFeedDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
